---
- name: Install apache httpd
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: yes

- name: copy files with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0640'
